(()=>{'use strict';
let clickAudio;
const SUPABASE_URL='https://lvxwziztdngntoqypzga.supabase.co';
const SUPABASE_KEY='sb_publishable_iCXNkHI8bgQ4c9BEVE9M3A_wOY1tvY';
function loadPremiumTheme(){if(document.getElementById('premium-reformulacao-css'))return;const l=document.createElement('link');l.id='premium-reformulacao-css';l.rel='stylesheet';l.href='premium-reformulacao.css?v=20260829';document.head.appendChild(l)}
function hardenMenu(){const btn=document.getElementById('menuBtn'),nav=document.getElementById('nav');if(!btn||!nav||btn.dataset.hardened==='1')return;btn.dataset.hardened='1';const close=()=>{nav.classList.remove('menu-open');btn.setAttribute('aria-expanded','false');btn.setAttribute('aria-label','Abrir menu')};btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=!nav.classList.contains('menu-open');nav.classList.toggle('menu-open',open);btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'Fechar menu':'Abrir menu')});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));document.addEventListener('click',e=>{if(nav.classList.contains('menu-open')&&!nav.contains(e.target)&&e.target!==btn)close()});window.addEventListener('resize',()=>{if(window.innerWidth>700)close()})}
function playClick(){try{if(!clickAudio)clickAudio=new Audio('mixkit-select-click-1109.wav');clickAudio.currentTime=0;clickAudio.volume=.82;const p=clickAudio.play();if(p)p.catch(()=>{})}catch(e){}}
function stopInfiniteLoading(){setTimeout(()=>document.querySelectorAll('.loading').forEach(el=>{if(/^Carregando/i.test(el.textContent.trim()))el.innerHTML='<div class="error-note">Nenhuma informação publicada no momento.</div>'}),7000)}
function renderHomePerformance(){if(!/\/home\.html$/i.test(location.pathname))return;const grid=document.querySelector('.result-grid');if(!grid||grid.dataset.performanceReady==='1')return;grid.dataset.performanceReady='1';const stats=[['🏟️','JOGOS','4'],['✅','VITÓRIAS','2'],['🤝','EMPATES','1'],['❌','DERROTAS','1'],['⚽','GOLS MARCADOS','7'],['🥅','GOLS SOFRIDOS','8'],['📈','SALDO DE GOLS','-1'],['🎯','APROVEITAMENTO','58,3%']];grid.innerHTML=stats.map(([i,l,v])=>'<div class="result-card"><b>'+i+' '+l+'</b><strong style="display:block;font-size:32px;line-height:1.1;margin-top:12px;color:#fff">'+v+'</strong><p style="margin-top:8px">Temporada 2026</p></div>').join('');if(!document.getElementById('performance-home-style')){const s=document.createElement('style');s.id='performance-home-style';s.textContent='.result-grid{grid-template-columns:repeat(4,1fr)}@media(max-width:900px){.result-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.result-grid{grid-template-columns:1fr 1fr}.result-card{padding:18px}.result-card strong{font-size:27px!important}}';document.head.appendChild(s)}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function loadSupabase(){try{const r=await fetch(SUPABASE_URL+'/rest/v1/jogos?select=*&status=neq.encerrado&order=data_jogo.asc,horario.asc',{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)return[];return await r.json()}catch(e){console.warn('Agenda:',e);return[]}}
function getCrest(j){return j.escudo_adversario||j.escudo_visitante||j.escudo_visitante_url||j.adversario_escudo||j.escudo_oponente||''}
function renderHomeUpcoming(jogos){if(!/\/home\.html$/i.test(location.pathname))return;const box=document.querySelector('#homeProximoJogo');if(!box||box.dataset.upcomingReady==='1')return;const upcoming=(jogos||[]).filter(j=>j.status!=='encerrado').sort((a,b)=>String(a.data_jogo||'').localeCompare(String(b.data_jogo||''))||String(a.horario||'').localeCompare(String(b.horario||''))).slice(0,1);if(!upcoming.length)return;box.dataset.upcomingReady='1';const j=upcoming[0];const adversario=String(j.adversario||j.oponente||j.time_adversario||j.visitante||'Adversário').trim().toUpperCase();const escudo=getCrest(j);const opponentImg=escudo?'<img src="'+esc(escudo)+'" alt="Escudo de '+esc(adversario)+'" onerror="this.style.display=\'none\'">':'<div class="match-placeholder"></div>';box.innerHTML='<div class="match-main"><div class="match-team"><img src="1000001685.png" alt="Escudo oficial de Baixa Grande"><strong>BAIXA GRANDE</strong></div><div class="match-vs">X</div><div class="match-team">'+opponentImg+'<strong>'+esc(adversario)+'</strong></div></div><div class="match-button"><a href="jogos.html">VER DETALHES DO JOGO</a></div>'}
async function initHome(){if(!/\/home\.html$/i.test(location.pathname))return;const jogos=await loadSupabase();renderHomeUpcoming(jogos)}
document.addEventListener('click',e=>{const target=e.target.closest('button,a,[role="button"],input[type="button"],input[type="submit"]');if(target)playClick()},{passive:true});
function init(){loadPremiumTheme();hardenMenu();stopInfiniteLoading();renderHomePerformance();initHome()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();