(()=>{'use strict';
let clickAudio;
const SUPABASE_URL='https://lvxwziztdngntoqypzga.supabase.co';
const SUPABASE_KEY='sb_publishable_iCXNkHI8bgQ4c9BEVE9M3A_wOY1tvY';
function playClick(){try{if(!clickAudio)clickAudio=new Audio('mixkit-select-click-1109.wav');clickAudio.currentTime=0;clickAudio.volume=.82;const p=clickAudio.play();if(p)p.catch(()=>{})}catch(e){}}
function setupMenu(){const nav=document.querySelector('#nav'),btn=document.querySelector('#menuBtn');if(!nav||!btn||nav.dataset.menuReady==='1')return;nav.dataset.menuReady='1';btn.setAttribute('aria-controls','nav');btn.setAttribute('aria-expanded','false')}
function closeMenu(){const nav=document.querySelector('#nav'),btn=document.querySelector('#menuBtn');if(nav)nav.classList.remove('menu-open');if(btn){btn.classList.remove('menu-open');btn.setAttribute('aria-expanded','false');btn.setAttribute('aria-label','Abrir menu')}}
function stopInfiniteLoading(){setTimeout(()=>document.querySelectorAll('.loading').forEach(el=>{if(/^Carregando/i.test(el.textContent.trim()))el.innerHTML='<div class="error-note">Nenhuma informação publicada no momento.</div>'}),7000)}
function renderHomePerformance(){if(!/\/home\.html$/i.test(location.pathname))return;const grid=document.querySelector('.result-grid');if(!grid||grid.dataset.performanceReady==='1')return;grid.dataset.performanceReady='1';const stats=[['🏟️','JOGOS','4'],['✅','VITÓRIAS','2'],['🤝','EMPATES','1'],['❌','DERROTAS','1'],['⚽','GOLS MARCADOS','7'],['🥅','GOLS SOFRIDOS','8'],['📈','SALDO DE GOLS','-1'],['🎯','APROVEITAMENTO','58,3%']];grid.innerHTML=stats.map(([i,l,v])=>'<div class="result-card"><b>'+i+' '+l+'</b><strong style="display:block;font-size:32px;line-height:1.1;margin-top:12px;color:#fff">'+v+'</strong><p style="margin-top:8px">Temporada 2026</p></div>').join('');if(!document.getElementById('performance-home-style')){const s=document.createElement('style');s.id='performance-home-style';s.textContent='.result-grid{grid-template-columns:repeat(4,1fr)}@media(max-width:900px){.result-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.result-grid{grid-template-columns:1fr 1fr}.result-card{padding:18px}.result-card strong{font-size:27px!important}}';document.head.appendChild(s)}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function dateBR(d){return d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'long',year:'numeric'}):'A definir'}
function renderHomeUpcoming(jogos){if(!/\/home\.html$/i.test(location.pathname))return;const old=document.querySelector('.match-card');if(!old||old.dataset.upcomingReady==='1')return;const upcoming=(jogos||[]).filter(j=>j.status!=='encerrado').sort((a,b)=>String(a.data_jogo+a.horario).localeCompare(String(b.data_jogo+b.horario))).slice(0,1);if(!upcoming.length)return;old.dataset.upcomingReady='1';const j=upcoming[0];const parts=String(j.observacoes||'').split('|').map(x=>x.trim());const rodada=parts[0]||'Terceira Rodada';const categoria=parts[1]||'Futsal Feminino';old.innerHTML='<div style="font-size:10px;letter-spacing:2px;color:#ff5660;font-weight:900">'+esc(j.competicao||'Copa Regional de Futsal Feminino 2026')+'</div><div style="font-size:11px;color:#9a9da3;font-weight:800;margin-top:6px">'+esc(rodada)+' • '+esc(categoria)+'</div><div class="match-main" style="margin-top:18px"><div class="match-team"><img src="1000001685.png" alt="Escudo oficial de Baixa Grande"><strong>BAIXA GRANDE</strong></div><div class="match-vs">X</div><div class="match-team"><img src="images.png" alt="Escudo de Mundo Novo" onerror="this.remove()"><strong>MUNDO NOVO</strong></div></div><div class="match-meta">📅 <strong>'+dateBR(j.data_jogo)+'</strong> · 🕒 <strong>'+esc(String(j.horario||'').slice(0,5))+'</strong><br>🏟️ '+esc(j.local||'Ginásio de Esportes')+'<br><strong>FUTSAL FEMININO</strong></div><div style="text-align:center;margin-top:18px"><a class="card-btn" href="jogos.html">ABRIR JOGO</a></div>'}
async function loadSupabase(){try{const r=await fetch(SUPABASE_URL+'/rest/v1/jogos?select=*&status=neq.encerrado&order=data_jogo.asc,horario.asc',{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY}});if(!r.ok)return[];return await r.json()}catch(e){console.warn('Agenda:',e);return[]}}
async function initHome(){if(!/\/home\.html$/i.test(location.pathname))return;let jogos=await loadSupabase();if(!jogos.length)jogos=[{competicao:'Copa Regional de Futsal Feminino 2026',data_jogo:'2026-08-22',horario:'19:00:00',local:'Ginásio de Esportes',adversario:'Mundo Novo',escudo_adversario:'images.png',status:'agendado',observacoes:'Terceira Rodada | Futsal Feminino'}];renderHomeUpcoming(jogos)}
document.addEventListener('click',e=>{const nav=document.querySelector('#nav'),btn=document.querySelector('#menuBtn');const target=e.target.closest('button,a,[role="button"],input[type="button"],input[type="submit"]');if(!target)return;playClick();if(target===btn&&nav){e.preventDefault();e.stopImmediatePropagation();const open=nav.classList.toggle('menu-open');btn.classList.toggle('menu-open',open);btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');return}if(nav&&nav.classList.contains('menu-open')&&!nav.contains(e.target)&&target!==btn)closeMenu();if(target.tagName==='A'&&target.href&&!target.hasAttribute('download')&&!target.href.startsWith('javascript:')&&target.target!=='_blank'){if(nav&&nav.contains(target))closeMenu();e.preventDefault();const h=target.href;setTimeout(()=>location.href=h,180)}},{capture:true});
function init(){setupMenu();stopInfiniteLoading();renderHomePerformance();initHome()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();