const SUPABASE_URL='https://lvxwziztdngntoqypzga.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_iCXNkHI8bgQ4c9BEVE9M3A_wOY1tvzY';
const supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY)||null;
const app=document.getElementById('app'),screen=document.getElementById('screen'),installBtn=document.getElementById('installBtn');let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn?.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
const content={news:['Notícias','Confira as notícias oficiais da Seleção de Baixa Grande.'],games:['Jogos','Próximos jogos, horários, locais e competições.'],results:['Resultados','Resultados oficiais e placares das partidas.'],squad:['Elenco','Atletas e categorias da Seleção de Baixa Grande.']};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadData(name){
 if(!supabaseClient){screen.innerHTML+='<div class="empty-state">Conexão com o banco indisponível.</div>';return}
 let data,error;
 if(name==='news'){({data,error}=await supabaseClient.from('noticias').select('id,titulo,resumo,imagem,criado_em,publicado').eq('publicado',true).order('criado_em',{ascending:false}).limit(20))}
 if(name==='games'||name==='results'){let q=supabaseClient.from('jogos').select('id,adversario,competicao,data_jogo,horario,local,status,gols_baixa_grande,gols_adversario,escudo_adversario').order('data_jogo',{ascending:true}).limit(30);if(name==='games')q=q.neq('status','encerrado');else q=q.eq('status','encerrado');({data,error}=await q)}
 if(name==='squad'){({data,error}=await supabaseClient.from('Atletas').select('id,nome,categoria,posicao,numero_camisa,foto,status_atleta,status').order('nome',{ascending:true}).limit(100))}
 if(error||!data?.length){screen.insertAdjacentHTML('beforeend',`<div class="empty-state">${error?'Não foi possível carregar os dados agora.':'Nenhum conteúdo oficial publicado ainda.'}</div>`);return}
 const box=document.createElement('div');box.className='data-list';
 data.forEach(item=>{const card=document.createElement('article');card.className='data-card';if(name==='news')card.innerHTML=`${item.imagem?`<img src="${esc(item.imagem)}" alt="">`:''}<div><small>NOTÍCIA OFICIAL</small><h3>${esc(item.titulo)}</h3><p>${esc(item.resumo||'')}</p></div>`;else if(name==='squad')card.innerHTML=`${item.foto?`<img src="${esc(item.foto)}" alt="${esc(item.nome)}">`:''}<div><small>${esc(item.categoria||'ELENCO')}</small><h3>${esc(item.nome)}</h3><p>${esc(item.posicao||'Atleta')}${item.numero_camisa?` • Camisa ${esc(item.numero_camisa)}`:''}</p></div>`;else card.innerHTML=`<div><small>${esc(item.competicao||'JOGO')}</small><h3>Baixa Grande × ${esc(item.adversario)}</h3><p>${esc(item.data_jogo||'')} ${esc(item.horario||'')} • ${esc(item.local||'')}</p>${name==='results'?`<strong>${esc(item.gols_baixa_grande??'-')} × ${esc(item.gols_adversario??'-')}</strong>`:''}</div>`;box.appendChild(card)});screen.appendChild(box)
}
async function openScreen(name){if(name==='home'){screen.hidden=true;document.querySelector('.hero').hidden=false;document.querySelectorAll('.section').forEach(x=>x.hidden=false)}else if(name==='assistant'){document.querySelector('.hero').hidden=true;document.querySelectorAll('.section').forEach(x=>x.hidden=true);screen.hidden=false;screen.innerHTML='<button class="back" data-screen="home">‹ Voltar</button><div class="assistant-head"><div class="assistant-icon">✦</div><div><h2>Assistente da Seleção</h2><p>Assistente editorial oficial.</p></div></div><div class="command-list"><button data-command="/TEXT">/TEXT <small>Texto profissional</small></button><button data-command="/NEWS">/NEWS <small>Notícia</small></button><button data-command="/TITLE">/TITLE <small>Título</small></button><button data-command="/CAPTION">/CAPTION <small>Legenda</small></button><button data-command="/RESULT">/RESULT <small>Resultado</small></button><button data-command="/GAME">/GAME <small>Jogo</small></button><button data-command="/TRAINING">/TRAINING <small>Treino</small></button><button data-command="/INSTAGRAM">/INSTAGRAM <small>Instagram</small></button></div><div class="chat" id="chat"><div class="bubble">Olá! Sou o Assistente da Seleção. Escolha um comando ou escreva seu pedido.</div></div><form class="chat-form" id="chatForm"><input id="chatInput" autocomplete="off" placeholder="Digite seu pedido..."><button>Enviar</button></form>';document.getElementById('chatForm').addEventListener('submit',sendChat);document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('chatInput').value=b.dataset.command+' ';document.getElementById('chatInput').focus()}))}else{document.querySelector('.hero').hidden=true;document.querySelectorAll('.section').forEach(x=>x.hidden=true);screen.hidden=false;screen.innerHTML=`<button class="back" data-screen="home">‹ Voltar</button><h2>${content[name][0]}</h2><p>${content[name][1]}</p><div class="empty-state">Carregando conteúdo oficial…</div>`;await loadData(name);screen.querySelector('.empty-state')?.remove()}document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.screen===name))}
async function sendChat(e){e.preventDefault();const input=document.getElementById('chatInput'),text=input.value.trim();if(!text)return;const chat=document.getElementById('chat');const me=document.createElement('div');me.className='bubble me';me.textContent=text;chat.appendChild(me);input.value='';const loading=document.createElement('div');loading.className='bubble';loading.textContent='Preparando resposta…';chat.appendChild(loading);try{const{data,error}=await supabaseClient.functions.invoke('selecaobot',{body:{message:text}});if(error)throw error;loading.textContent=data?.answer||'Não recebi uma resposta.'}catch(err){loading.textContent='Não foi possível conectar ao Assistente agora.'}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b)openScreen(b.dataset.screen)});
