const SUPABASE_URL='https://lvxwziztdngntoqypzga.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='CONFIGURE_NO_SUPABASE_DASHBOARD';
const supabaseClient=(window.supabase&&SUPABASE_PUBLISHABLE_KEY.startsWith('sb_'))?window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY):null;
const app=document.getElementById('app'),screen=document.getElementById('screen'),installBtn=document.getElementById('installBtn');let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.hidden=true});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
const content={news:['Notícias','As notícias oficiais da Seleção aparecerão aqui quando o conteúdo estiver conectado ao Supabase.'],games:['Jogos','Próximos jogos, horários, locais e competições.'],results:['Resultados','Resultados oficiais e placares das partidas.'],squad:['Elenco','Atletas e categorias da Seleção de Baixa Grande.']};
function openScreen(name){if(name==='home'){screen.hidden=true;document.querySelector('.hero').hidden=false;document.querySelectorAll('.section').forEach(x=>x.hidden=false)}else if(name==='assistant'){document.querySelector('.hero').hidden=true;document.querySelectorAll('.section').forEach(x=>x.hidden=true);screen.hidden=false;screen.innerHTML='<button class="back" data-screen="home">‹ Voltar</button><div class="assistant-head"><div class="assistant-icon">✦</div><div><h2>Assistente da Seleção</h2><p>Assistente editorial oficial.</p></div></div><div class="command-list"><button data-command="/TEXT">/TEXT <small>Texto profissional</small></button><button data-command="/NEWS">/NEWS <small>Notícia</small></button><button data-command="/TITLE">/TITLE <small>Título</small></button><button data-command="/CAPTION">/CAPTION <small>Legenda</small></button><button data-command="/RESULT">/RESULT <small>Resultado</small></button><button data-command="/GAME">/GAME <small>Jogo</small></button><button data-command="/TRAINING">/TRAINING <small>Treino</small></button><button data-command="/INSTAGRAM">/INSTAGRAM <small>Instagram</small></button></div><div class="chat" id="chat"><div class="bubble">Olá! Sou o Assistente da Seleção. Escolha um comando ou escreva seu pedido.</div></div><form class="chat-form" id="chatForm"><input id="chatInput" autocomplete="off" placeholder="Digite seu pedido..."><button>Enviar</button></form>';document.getElementById('chatForm').addEventListener('submit',sendChat);document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('chatInput').value=b.dataset.command+' ';document.getElementById('chatInput').focus()}))}else{document.querySelector('.hero').hidden=true;document.querySelectorAll('.section').forEach(x=>x.hidden=true);screen.hidden=false;screen.innerHTML=`<button class="back" data-screen="home">‹ Voltar</button><h2>${content[name][0]}</h2><p>${content[name][1]}</p><div class="empty-state">Esta área está preparada para receber os dados oficiais da Seleção.</div>`}document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.screen===name))}
async function sendChat(e){e.preventDefault();const input=document.getElementById('chatInput'),text=input.value.trim();if(!text)return;const chat=document.getElementById('chat');const me=document.createElement('div');me.className='bubble me';me.textContent=text;chat.appendChild(me);input.value='';const loading=document.createElement('div');loading.className='bubble';loading.textContent='Preparando resposta…';chat.appendChild(loading);if(!supabaseClient){loading.textContent='O Assistente está pronto. Falta apenas configurar a chave pública do Supabase para ativar a conexão com o backend.';return}try{const{data,error}=await supabaseClient.functions.invoke('selecaobot',{body:{message:text}});if(error)throw error;loading.textContent=data?.answer||'Não recebi uma resposta.'}catch(err){loading.textContent='Não foi possível conectar ao Assistente agora.'}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b)openScreen(b.dataset.screen)});
