const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const SB_URL=window.SUPABASE_URL||'';
const SB_KEY=window.SUPABASE_ANON_KEY||'';
let accessToken=localStorage.getItem('sb_admin_access_token')||'',refreshToken=localStorage.getItem('sb_admin_refresh_token')||'',editingId=null,coverUrl=null,loginBusy=false;
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function loginMessage(msg,type='error'){const el=$('#loginMessage');if(!el)return;el.textContent=msg;el.className='notice '+type}
function slugify(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setStatus(text,ok=false){const s=$('#connectionStatus');if(s)s.textContent=text;const dot=s?.previousElementSibling;if(dot)dot.classList.toggle('ok',ok)}
function show(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={dashboard:'Visão geral',news:'Notícias',editor:editingId?'Editar notícia':'Nova notícia',games:'Jogos',gameEditor:'Novo jogo',athletes:'Elenco',athEditor:'Novo atleta',gallery:'Galeria',galleryEditor:'Nova imagem'};if($('#pageTitle'))$('#pageTitle').textContent=titles[view]||'Painel';if(view==='news')loadNews()}
function authHeaders(){return {'apikey':SB_KEY,'Authorization':`Bearer ${accessToken}`,'Content-Type':'application/json'}}
async function api(path,options={}){const headers={...(options.headers||{}),apikey:SB_KEY};if(accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(SB_URL+path,{...options,headers});let data=null;try{data=await r.json()}catch{}if(!r.ok){const e=new Error(data?.message||data?.error_description||data?.error||`HTTP ${r.status}`);e.status=r.status;e.data=data;throw e}return data}
async function signIn(email,password){const r=await fetch(SB_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.error_description||data?.msg||'Login inválido');accessToken=data.access_token;refreshToken=data.refresh_token||'';localStorage.setItem('sb_admin_access_token',accessToken);if(refreshToken)localStorage.setItem('sb_admin_refresh_token',refreshToken);return data}
function signOut(){accessToken='';refreshToken='';localStorage.removeItem('sb_admin_access_token');localStorage.removeItem('sb_admin_refresh_token');$('#app').hidden=true;$('#login').classList.add('active');setStatus('Faça login');loginMessage('');}
async function requireAdmin(){
  if(!SB_URL||!SB_KEY){setStatus('Erro de configuração');loginMessage('Configuração do Supabase ausente.');return false}
  if(!accessToken){$('#app').hidden=true;$('#login').classList.add('active');setStatus('Faça login');return false}
  try{
    const rows=await api('/rest/v1/admin_users?select=user_id&limit=1');
    if(!Array.isArray(rows)||!rows.length){signOut();setStatus('Acesso negado');loginMessage('Acesso negado. Esta conta não possui permissão administrativa.');return false}
    $('#login').classList.remove('active');$('#app').hidden=false;setStatus('Supabase conectado',true);loginMessage('');await loadStats();await loadNews();return true;
  }catch(e){console.error('Admin authorization error:',e);if(e.status===401||e.status===403)signOut();else{setStatus('Erro de conexão');loginMessage('Não foi possível verificar seu acesso. Tente novamente.')}return false}
}
async function doLogin(){
  if(loginBusy)return;
  if(!SB_URL||!SB_KEY){loginMessage('Configuração do Supabase ausente.');return}
  const email=$('#loginEmail')?.value.trim()||'',password=$('#loginPassword')?.value||'',btn=$('#loginBtn');
  if(!email||!password){loginMessage('Informe o e-mail e a senha.');return}
  loginBusy=true;if(btn){btn.disabled=true;btn.textContent='Entrando...'}loginMessage('Entrando...','loading');setStatus('Autenticando...');
  try{await signIn(email,password);const ok=await requireAdmin();if(!ok)signOut();}
  catch(e){console.error('Login error:',e);const msg=(e.message||'').toLowerCase();if(msg.includes('invalid login credentials')||msg.includes('invalid credentials'))loginMessage('E-mail ou senha incorretos. Confira os dados e tente novamente.');else if(msg.includes('email not confirmed'))loginMessage('O e-mail ainda não foi confirmado no Supabase.');else if(msg.includes('too many requests'))loginMessage('Muitas tentativas. Aguarde um pouco e tente novamente.');else loginMessage('Não foi possível entrar. Tente novamente.');setStatus('Falha no login')}
  finally{loginBusy=false;if(btn){btn.disabled=false;btn.textContent='Entrar'}}
}
function bindLogin(){const btn=$('#loginBtn'),form=$('#loginForm');if(!btn||!form){console.error('Admin login elements not found');return}btn.addEventListener('click',e=>{e.preventDefault();doLogin()});form.addEventListener('submit',e=>{e.preventDefault();doLogin()});window.adminLogin=doLogin}
$$('.nav[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
async function loadStats(){try{const data=await api('/rest/v1/news?select=status');const total=data.length,d=data.filter(n=>n.status==='draft'||n.status==='unpublished').length,p=data.filter(n=>n.status==='published').length;$('#statNews').textContent=total;$('#statDraft').textContent=d;$('#statPublished').textContent=p}catch(e){toast('Erro ao carregar notícias.')}}
async function loadNews(){const box=$('#newsList');if(!box)return;box.innerHTML='<div class="empty">Carregando notícias...</div>';try{const data=await api('/rest/v1/news?select=*&order=created_at.desc');if(!data.length){box.innerHTML='<div class="empty">Nenhuma notícia cadastrada ainda.</div>';return}box.innerHTML=data.map(n=>`<article class="panel"><div class="panel-head"><div><small>${esc(n.category||'Notícias')} • ${esc(n.status)}</small><h3>${esc(n.title)}</h3></div><div class="actions"><button type="button" class="ghost" data-edit="${n.id}">Editar</button>${n.status==='published'?`<button type="button" class="ghost" data-toggle="${n.id}" data-status="unpublished">Despublicar</button>`:`<button type="button" class="ghost" data-toggle="${n.id}" data-status="published">Publicar</button>`}<button type="button" class="ghost" data-delete="${n.id}">Excluir</button></div></div><p class="muted">${esc(n.subtitle||'')}</p><small class="muted">${n.published_at?new Date(n.published_at).toLocaleString('pt-BR'):'Sem publicação'}</small></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editNews(b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>setNewsStatus(b.dataset.toggle,b.dataset.status));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteNews(b.dataset.delete));await loadStats()}catch(e){console.error(e);box.innerHTML='<div class="empty">Não foi possível carregar as notícias.</div>'}}
async function editNews(id){try{const data=(await api(`/rest/v1/news?select=*&id=eq.${encodeURIComponent(id)}&limit=1`))[0];if(!data)return;editingId=id;coverUrl=data.cover_image||null;$('#title').value=data.title||'';$('#subtitle').value=data.subtitle||'';$('#category').value=data.category||'Notícias';$('#author').value=data.author||'';$('#content').innerHTML=data.content||'';$('#seoTitle').value=data.seo_title||'';$('#slug').value=data.slug||'';$('#slug').dataset.manual='1';$('#seoDescription').value=data.seo_description||'';updateCover();show('editor')}catch(e){toast('Erro ao abrir notícia.')}}
function collect(){return{title:$('#title').value.trim(),subtitle:$('#subtitle').value.trim(),category:$('#category').value,author:$('#author').value.trim()||'Seleção de Baixa Grande',content:$('#content').innerHTML.trim(),seo_title:$('#seoTitle').value.trim()||$('#title').value.trim().slice(0,70),slug:$('#slug').value.trim()||slugify($('#title').value),seo_description:$('#seoDescription').value.trim()}}
async function uploadCover(){const f=$('#coverFile').files[0];if(!f)return coverUrl;const ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`covers/${crypto.randomUUID()}.${ext}`;const r=await fetch(`${SB_URL}/storage/v1/object/news/${path}`,{method:'POST',headers:{apikey:SB_KEY,Authorization:`Bearer ${accessToken}`,'Content-Type':f.type||'image/jpeg','x-upsert':'false'},body:f});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.message||'Erro ao enviar imagem')}coverUrl=`${SB_URL}/storage/v1/object/public/news/${path}`;return coverUrl}
async function saveNews(status){const n=collect();if(!n.title)return toast('Informe o título.');try{const image=await uploadCover();const row={title:n.title,slug:n.slug,subtitle:n.subtitle,content:n.content,cover_image:image,category:n.category,author:n.author,status,published_at:status==='published'?new Date().toISOString():null,seo_title:n.seo_title,seo_description:n.seo_description,og_image:image};if(editingId)await api(`/rest/v1/news?id=eq.${encodeURIComponent(editingId)}`,{method:'PATCH',headers:{Prefer:'return=minimal','Content-Type':'application/json'},body:JSON.stringify(row)});else{const r=await api('/rest/v1/news',{method:'POST',headers:{Prefer:'return=representation','Content-Type':'application/json'},body:JSON.stringify(row)});if(r?.[0])editingId=r[0].id}toast(status==='published'?'Notícia publicada.':'Rascunho salvo.');await loadStats();show('news')}catch(e){console.error(e);toast('Não foi possível salvar: '+(e.message||'erro'))}}
function bindEditor(){const d=$('#draftBtn'),nf=$('#newsForm'),t=$('#title'),sl=$('#slug'),sf=$('#coverFile');if(d)d.onclick=()=>saveNews('draft');if(nf)nf.onsubmit=e=>{e.preventDefault();saveNews('published')};if(t)t.oninput=()=>{if(!sl.dataset.manual)sl.value=slugify(t.value);if(!$('#seoTitle').value)$('#seoTitle').value=t.value.slice(0,70)};if(sl)sl.oninput=e=>e.target.dataset.manual='1';if(sf)sf.onchange=updateCover}
async function setNewsStatus(id,status){try{await api(`/rest/v1/news?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal','Content-Type':'application/json'},body:JSON.stringify({status,published_at:status==='published'?new Date().toISOString():null})});toast(status==='published'?'Publicado.':'Despublicado.');loadNews()}catch(e){toast('Erro ao alterar publicação.')}}
async function deleteNews(id){if(!confirm('Excluir esta notícia?'))return;try{await api(`/rest/v1/news?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});toast('Notícia excluída.');loadNews()}catch(e){toast('Erro ao excluir.')}}
function updateCover(){const f=$('#coverFile')?.files[0],p=$('#coverPreview');if(!p)return;if(f){p.style.backgroundImage=`url(${URL.createObjectURL(f)})`;p.querySelector('span').style.display='none'}else if(coverUrl){p.style.backgroundImage=`url(${coverUrl})`;p.querySelector('span').style.display='none'}else{p.style.backgroundImage='none';p.querySelector('span').style.display='block'}}
function init(){try{bindLogin();bindEditor();$$('.nav[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));if(!SB_URL||!SB_KEY)throw new Error('Supabase configuration missing');window.adminApi=api;requireAdmin()}catch(e){console.error('Admin init error:',e);setStatus('Erro de configuração');loginMessage('Erro ao carregar o sistema de autenticação. Recarregue a página.')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();