const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let drafts=JSON.parse(localStorage.getItem('sb_admin_news')||'[]');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function slugify(v){return v.toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)}
function show(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={dashboard:'Visão geral',news:'Notícias',editor:'Nova notícia'};$('#pageTitle').textContent=titles[view]||'Painel';if(view==='news')renderNews()}
$$('.nav[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));
function renderNews(){const box=$('#newsList');if(!drafts.length){box.innerHTML='<div class="empty">Nenhuma notícia local ainda.<br>Crie um rascunho para testar o editor.</div>';return}box.innerHTML=drafts.map((n,i)=>`<article class="panel"><div class="panel-head"><div><small>${n.category}</small><h3>${escapeHtml(n.title||'Sem título')}</h3></div><button class="ghost" data-edit="${i}">Editar</button></div><p class="muted">${escapeHtml(n.subtitle||'Sem subtítulo')}</p><small class="muted">${n.status==='draft'?'RASCUNHO':'PREPARADA'} • ${new Date(n.updatedAt).toLocaleString('pt-BR')}</small></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>loadDraft(+b.dataset.edit))}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function collect(){return{title:$('#title').value.trim(),subtitle:$('#subtitle').value.trim(),category:$('#category').value,author:$('#author').value.trim(),cover:$('#cover').value.trim(),content:$('#content').innerHTML,seoTitle:$('#seoTitle').value.trim(),slug:$('#slug').value.trim()||slugify($('#title').value),seoDescription:$('#seoDescription').value.trim(),status:'draft',updatedAt:new Date().toISOString()}}
function save(){const n=collect();if(!n.title){toast('Informe o título da notícia.');$('#title').focus();return}drafts.unshift(n);drafts=drafts.slice(0,30);localStorage.setItem('sb_admin_news',JSON.stringify(drafts));updateStats();toast('Rascunho salvo neste navegador.');return n}
function loadDraft(i){const n=drafts[i];$('#title').value=n.title||'';$('#subtitle').value=n.subtitle||'';$('#category').value=n.category||'Notícias';$('#author').value=n.author||'';$('#cover').value=n.cover||'';$('#content').innerHTML=n.content||'';$('#seoTitle').value=n.seoTitle||'';$('#slug').value=n.slug||'';$('#seoDescription').value=n.seoDescription||'';updateCover();show('editor');toast('Rascunho carregado.')}
function updateStats(){const c=drafts.length,p=drafts.filter(x=>x.status==='published').length;$('#statNews').textContent=c;$('#statDraft').textContent=c-p;$('#statPublished').textContent=p}
$('#title').addEventListener('input',()=>{if(!$('#slug').value||$('#slug').dataset.manual!=='1')$('#slug').value=slugify($('#title').value);if(!$('#seoTitle').value)$('#seoTitle').value=$('#title').value.slice(0,70)});$('#slug').addEventListener('input',e=>e.target.dataset.manual='1');$('#cover').addEventListener('input',updateCover);function updateCover(){const p=$('#coverPreview'),u=$('#cover').value.trim();p.style.backgroundImage=u?`url("${u.replace(/"/g,'')}" )`:'none';p.querySelector('span').style.display=u?'none':'block'}
$$('[data-cmd]').forEach(b=>b.onclick=()=>{const c=b.dataset.cmd;if(c==='createLink'){const u=prompt('URL do link:');if(u)document.execCommand(c,false,u)}else document.execCommand(c,false,b.dataset.value||null);$('#content').focus()});
$('#draftBtn').onclick=save;$('#newsForm').onsubmit=e=>{e.preventDefault();const n=save();if(n)toast('Notícia preparada para publicação. A conexão com o Supabase ainda não está ativa.')};$('#previewBtn').onclick=()=>{const n=collect();if(!n.title){toast('Informe o título primeiro.');return}const w=window.open('','_blank');w.document.write(`<html lang="pt-BR"><head><meta charset="utf-8"><title>${escapeHtml(n.title)}</title><style>body{margin:0;background:#070708;color:#f5f5f5;font:16px Arial;line-height:1.8}.wrap{max-width:850px;margin:auto;padding:50px 20px}small{color:#ed2733;font-weight:bold}h1{font:700 48px Georgia;line-height:1.05}h2{font-size:28px}img{max-width:100%;border-radius:12px}article{color:#c7cbd0}</style></head><body><main class="wrap"><small>${escapeHtml(n.category)}</small><h1>${escapeHtml(n.title)}</h1><p>${escapeHtml(n.subtitle)}</p>${n.cover?`<img src="${escapeHtml(n.cover)}">`:''}<article>${n.content}</article></main></body></html>`);w.document.close()};
updateStats();renderNews();
