const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const supabase=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
let editingId=null,coverPath=null,coverUrl=null;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function slugify(v){return v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,100)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={dashboard:'Visão geral',news:'Notícias',editor:editingId?'Editar notícia':'Nova notícia'};$('#pageTitle').textContent=titles[view]||'Painel';if(view==='news')loadNews();}
$$('.nav[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
function setStatus(text,ok=false){$('#connectionStatus').textContent=text;$('#connectionStatus').previousElementSibling?.classList.toggle('ok',ok)}
async function requireAdmin(){const {data:{session}}=await supabase.auth.getSession();if(!session){$('#login').classList.add('active');$('#app').hidden=true;setStatus('Faça login');return false}const {data,isAdminError}=await supabase.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(isAdminError||!data){await supabase.auth.signOut();$('#loginMessage').textContent='Esta conta não possui autorização de administrador.';$('#login').classList.add('active');$('#app').hidden=true;setStatus('Acesso negado');return false}$('#login').classList.remove('active');$('#app').hidden=false;setStatus('Supabase conectado',true);await loadStats();await loadNews();return true}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMessage').textContent='Entrando...';const {error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});if(error){$('#loginMessage').textContent=error.message;return}$('#loginMessage').textContent='';await requireAdmin()};
supabase.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')requireAdmin()});
async function loadStats(){const {data,error}=await supabase.from('news').select('status');if(error){toast('Erro ao carregar notícias.');return}const total=data.length,d=data.filter(n=>n.status==='draft'||n.status==='unpublished').length,p=data.filter(n=>n.status==='published').length;$('#statNews').textContent=total;$('#statDraft').textContent=d;$('#statPublished').textContent=p}
async function loadNews(){const box=$('#newsList');box.innerHTML='<div class="empty">Carregando notícias...</div>';const {data,error}=await supabase.from('news').select('*').order('created_at',{ascending:false});if(error){box.innerHTML='<div class="empty">Não foi possível carregar as notícias.</div>';return}if(!data.length){box.innerHTML='<div class="empty">Nenhuma notícia cadastrada ainda.</div>';return}box.innerHTML=data.map(n=>`<article class="panel"><div class="panel-head"><div><small>${esc(n.category||'Notícias')} • ${esc(n.status)}</small><h3>${esc(n.title)}</h3></div><div class="actions"><button class="ghost" data-edit="${n.id}">Editar</button>${n.status==='published'?`<button class="ghost" data-toggle="${n.id}" data-status="unpublished">Despublicar</button>`:`<button class="ghost" data-toggle="${n.id}" data-status="published">Publicar</button>`}<button class="ghost" data-delete="${n.id}">Excluir</button></div></div><p class="muted">${esc(n.subtitle||'')}</p><small class="muted">${n.published_at?new Date(n.published_at).toLocaleString('pt-BR'):'Sem publicação'}</small></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editNews(b.dataset.edit));$$('[data-toggle]').forEach(b=>b.onclick=()=>setNewsStatus(b.dataset.toggle,b.dataset.status));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteNews(b.dataset.delete));await loadStats()}
async function editNews(id){const {data,error}=await supabase.from('news').select('*').eq('id',id).single();if(error)return toast('Erro ao abrir notícia.');editingId=id;coverPath=null;coverUrl=data.cover_image||null;$('#title').value=data.title||'';$('#subtitle').value=data.subtitle||'';$('#category').value=data.category||'Notícias';$('#author').value=data.author||'';$('#content').innerHTML=data.content||'';$('#seoTitle').value=data.seo_title||'';$('#slug').value=data.slug||'';$('#seoDescription').value=data.seo_description||'';updateCover();show('editor')}
function collect(){return{title:$('#title').value.trim(),subtitle:$('#subtitle').value.trim(),category:$('#category').value,author:$('#author').value.trim()||'Seleção de Baixa Grande',content:$('#content').innerHTML.trim(),seo_title:$('#seoTitle').value.trim()||$('#title').value.trim().slice(0,70),slug:$('#slug').value.trim()||slugify($('#title').value),seo_description:$('#seoDescription').value.trim()}}
async function uploadCover(){const f=$('#coverFile').files[0];if(!f)return coverUrl;const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`covers/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('news').upload(path,f,{upsert:false,contentType:f.type,cacheControl:'31536000'});if(error)throw error;coverPath=path;const {data}=supabase.storage.from('news').getPublicUrl(path);coverUrl=data.publicUrl;return coverUrl}
async function saveNews(status){const n=collect();if(!n.title)return toast('Informe o título.');try{const image=await uploadCover();const row={title:n.title,slug:n.slug,subtitle:n.subtitle,content:n.content,cover_image:image,category:n.category,author:n.author,status,published_at:status==='published'?new Date().toISOString():null,seo_title:n.seo_title,seo_description:n.seo_description,og_image:image};let error;if(editingId){({error}=await supabase.from('news').update(row).eq('id',editingId))}else{const r=await supabase.from('news').insert(row).select('id').single();error=r.error;if(!error)editingId=r.data.id}if(error)throw error;toast(status==='published'?'Notícia publicada.':'Rascunho salvo.');await loadStats();await loadNews();show('news')}catch(e){toast('Não foi possível salvar: '+(e.message||'erro'))}}
$('#draftBtn').onclick=()=>saveNews('draft');$('#newsForm').onsubmit=e=>{e.preventDefault();saveNews('published')};
async function setNewsStatus(id,status){const {error}=await supabase.from('news').update({status,published_at:status==='published'?new Date().toISOString():null}).eq('id',id);if(error)toast('Erro ao alterar publicação.');else{toast(status==='published'?'Publicado.':'Despublicado.');loadNews()}}
async function deleteNews(id){if(!confirm('Excluir esta notícia?'))return;const {error}=await supabase.from('news').delete().eq('id',id);if(error)toast('Erro ao excluir.');else{toast('Notícia excluída.');loadNews()}}
$('#title').oninput=()=>{if(!$('#slug').dataset.manual)$('#slug').value=slugify($('#title').value);if(!$('#seoTitle').value)$('#seoTitle').value=$('#title').value.slice(0,70)};$('#slug').oninput=e=>e.target.dataset.manual='1';$('#coverFile').onchange=updateCover;function updateCover(){const f=$('#coverFile').files[0],p=$('#coverPreview');if(f){p.style.backgroundImage=`url(${URL.createObjectURL(f)})`;p.querySelector('span').style.display='none'}else if(coverUrl){p.style.backgroundImage=`url(${coverUrl})`;p.querySelector('span').style.display='none'}else{p.style.backgroundImage='none';p.querySelector('span').style.display='block'}}
$$('[data-cmd]').forEach(b=>b.onclick=()=>{if(b.dataset.cmd==='createLink'){const u=prompt('URL do link:');if(u)document.execCommand('createLink',false,u)}else document.execCommand(b.dataset.cmd,false,b.dataset.value||null);$('#content').focus()});
$('#newBtn').onclick=()=>{editingId=null;coverUrl=null;coverPath=null;$('#newsForm').reset();$('#content').innerHTML='';$('#slug').dataset.manual='';updateCover();show('editor')};
$('#previewBtn').onclick=()=>{const n=collect(),w=window.open('','_blank');if(!w)return;w.document.write(`<html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(n.title)}</title><style>body{margin:0;background:#070708;color:#f5f5f5;font:16px Arial;line-height:1.8}.wrap{max-width:850px;margin:auto;padding:50px 20px}small{color:#ed2733;font-weight:bold}h1{font:700 48px Georgia;line-height:1.05}img{max-width:100%;border-radius:12px}article{color:#c7cbd0}</style></head><body><main class="wrap"><small>${esc(n.category)}</small><h1>${esc(n.title)}</h1><p>${esc(n.subtitle)}</p>${coverUrl?`<img src="${esc(coverUrl)}">`:''}<article>${n.content}</article></main></body></html>`);w.document.close()};
requireAdmin();
