(()=>{
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let gameId=null, athleteId=null, galleryId=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sup=()=>window.adminSupabase||null;
function status(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function showModule(id,title){if(typeof window.show==='function')window.show(id);const h=$('#pageTitle');if(h)h.textContent=title}
async function loadGames(){const s=sup();if(!s)return;const box=$('#gamesList');if(!box)return;box.innerHTML='<div class="empty">Carregando jogos...</div>';const {data,error}=await s.from('jogos').select('*').order('data_jogo',{ascending:false});if(error){box.innerHTML='<div class="empty">Não foi possível carregar os jogos.</div>';return}if(!data?.length){box.innerHTML='<div class="empty">Nenhum jogo cadastrado.</div>';return}box.innerHTML=data.map(g=>`<article class="panel"><div class="panel-head"><div><small>${esc(g.status||'Agendado')} • ${esc(g.competicao||'')}</small><h3>Baixa Grande × ${esc(g.adversario)}</h3></div><div class="actions"><button class="ghost" data-game-edit="${g.id}">Editar</button><button class="ghost" data-game-del="${g.id}">Excluir</button></div></div><p class="muted">${esc(g.data_jogo)}${g.horario?' • '+esc(String(g.horario).slice(0,5)):''}${g.local?' • '+esc(g.local):''}</p><small class="muted">Placar: ${g.gols_baixa_grande} × ${g.gols_adversario}</small></article>`).join('');$$('[data-game-edit]').forEach(b=>b.onclick=()=>editGame(b.dataset.gameEdit));$$('[data-game-del]').forEach(b=>b.onclick=()=>deleteGame(b.dataset.gameDel))}
function resetGame(){gameId=null;['gameOpponent','gameCompetition','gameDate','gameTime','gameVenue','gameBadge','gameStatus','gameHomeGoals','gameAwayGoals','gameHighlight','gameNotes'].forEach(id=>{const e=$('#'+id);if(e)e.value=''});if($('#gameStatus'))$('#gameStatus').value='agendado';if($('#gameFormTitle'))$('#gameFormTitle').textContent='Novo jogo'}
async function editGame(id){const s=sup();const {data,error}=await s.from('jogos').select('*').eq('id',id).single();if(error)return status('Erro ao abrir jogo.');gameId=id;const m={gameOpponent:'adversario',gameCompetition:'competicao',gameDate:'data_jogo',gameTime:'horario',gameVenue:'local',gameBadge:'escudo_adversario',gameStatus:'status',gameHomeGoals:'gols_baixa_grande',gameAwayGoals:'gols_adversario',gameHighlight:'destaque',gameNotes:'observacoes'};Object.entries(m).forEach(([id,k])=>{if($('#'+id))$('#'+id).value=data[k]??''});if($('#gameFormTitle'))$('#gameFormTitle').textContent='Editar jogo';showModule('gameEditor','Editar jogo')}
async function saveGame(e){e.preventDefault();const s=sup();const row={adversario:$('#gameOpponent').value.trim(),competicao:$('#gameCompetition').value.trim(),data_jogo:$('#gameDate').value,horario:$('#gameTime').value||null,local:$('#gameVenue').value.trim(),escudo_adversario:$('#gameBadge').value.trim()||null,status:$('#gameStatus').value,gols_baixa_grande:Number($('#gameHomeGoals').value||0),gols_adversario:Number($('#gameAwayGoals').value||0),destaque:$('#gameHighlight').value.trim()||null,observacoes:$('#gameNotes').value.trim()||null};if(!row.adversario||!row.data_jogo)return status('Informe adversário e data.');const r=gameId?await s.from('jogos').update(row).eq('id',gameId):await s.from('jogos').insert(row);if(r.error)return status('Não foi possível salvar o jogo.');status(gameId?'Jogo atualizado.':'Jogo cadastrado.');resetGame();loadGames();showModule('games','Jogos')}
async function deleteGame(id){if(!confirm('Excluir este jogo?'))return;const r=await sup().from('jogos').delete().eq('id',id);status(r.error?'Erro ao excluir.':'Jogo excluído.');loadGames()}
async function loadAthletes(){const s=sup();if(!s)return;const box=$('#athletesList');if(!box)return;box.innerHTML='<div class="empty">Carregando elenco...</div>';const {data,error}=await s.from('Atletas').select('id,nome,categoria,posicao,numero_camisa,status,foto,instagram').order('nome');if(error){box.innerHTML='<div class="empty">Não foi possível carregar o elenco.</div>';return}if(!data?.length){box.innerHTML='<div class="empty">Nenhum atleta cadastrado.</div>';return}box.innerHTML=data.map(a=>`<article class="panel"><div class="panel-head"><div><small>${esc(a.categoria||'Sem categoria')} • ${esc(a.posicao||'')}</small><h3>${esc(a.nome)}</h3></div><div class="actions"><button class="ghost" data-ath-edit="${a.id}">Editar</button><button class="ghost" data-ath-del="${a.id}">Excluir</button></div></div><p class="muted">Camisa ${a.numero_camisa??'—'} • ${esc(a.status||'Ativo')}</p></article>`).join('');$$('[data-ath-edit]').forEach(b=>b.onclick=()=>editAthlete(b.dataset.athEdit));$$('[data-ath-del]').forEach(b=>b.onclick=()=>deleteAthlete(b.dataset.athDel))}
function resetAthlete(){athleteId=null;['athName','athEmail','athCategory','athPosition','athNumber','athPhoto','athInstagram','athStatus'].forEach(id=>{const e=$('#'+id);if(e)e.value=''});if($('#athStatus'))$('#athStatus').value='ativo';if($('#athFormTitle'))$('#athFormTitle').textContent='Novo atleta'}
async function editAthlete(id){const {data,error}=await sup().from('Atletas').select('id,nome,email,categoria,posicao,numero_camisa,foto,instagram,status').eq('id',id).single();if(error)return status('Erro ao abrir atleta.');athleteId=id;const m={athName:'nome',athEmail:'email',athCategory:'categoria',athPosition:'posicao',athNumber:'numero_camisa',athPhoto:'foto',athInstagram:'instagram',athStatus:'status'};Object.entries(m).forEach(([id,k])=>{if($('#'+id))$('#'+id).value=data[k]??''});if($('#athFormTitle'))$('#athFormTitle').textContent='Editar atleta';showModule('athEditor','Editar atleta')}
async function saveAthlete(e){e.preventDefault();const row={nome:$('#athName').value.trim(),email:$('#athEmail').value.trim(),categoria:$('#athCategory').value.trim()||null,posicao:$('#athPosition').value.trim()||null,numero_camisa:$('#athNumber').value?Number($('#athNumber').value):null,foto:$('#athPhoto').value.trim()||null,instagram:$('#athInstagram').value.trim()||null,status:$('#athStatus').value||'ativo'};if(!row.nome||!row.email)return status('Informe nome e e-mail.');const r=athleteId?await sup().from('Atletas').update(row).eq('id',athleteId):await sup().from('Atletas').insert(row);if(r.error)return status('Não foi possível salvar o atleta.');status(athleteId?'Atleta atualizado.':'Atleta cadastrado.');resetAthlete();loadAthletes();showModule('athletes','Elenco')}
async function deleteAthlete(id){if(!confirm('Excluir este atleta?'))return;const r=await sup().from('Atletas').delete().eq('id',id);status(r.error?'Erro ao excluir.':'Atleta excluído.');loadAthletes()}
async function loadGallery(){const s=sup();if(!s)return;const box=$('#galleryList');if(!box)return;box.innerHTML='<div class="empty">Carregando galeria...</div>';const {data,error}=await s.from('galeria').select('*').order('criado_em',{ascending:false});if(error){box.innerHTML='<div class="empty">Não foi possível carregar a galeria.</div>';return}if(!data?.length){box.innerHTML='<div class="empty">Nenhuma imagem cadastrada.</div>';return}box.innerHTML=data.map(g=>`<article class="panel"><div class="panel-head"><div><small>${g.ativo?'ATIVA':'INATIVA'}</small><h3>${esc(g.titulo||'Sem título')}</h3></div><div class="actions"><button class="ghost" data-gal-toggle="${g.id}">${g.ativo?'Desativar':'Ativar'}</button><button class="ghost" data-gal-del="${g.id}">Excluir</button></div></div><img src="${esc(g.imagem_url)}" alt="" style="width:100%;max-height:220px;object-fit:cover;border-radius:10px;margin-top:10px"><p class="muted">${esc(g.descricao||'')}</p></article>`).join('');$$('[data-gal-toggle]').forEach(b=>b.onclick=()=>toggleGallery(b.dataset.galToggle));$$('[data-gal-del]').forEach(b=>b.onclick=()=>deleteGallery(b.dataset.galDel))}
function resetGallery(){galleryId=null;['galTitle','galDescription','galUrl'].forEach(id=>{const e=$('#'+id);if(e)e.value=''});if($('#galActive'))$('#galActive').checked=true}
async function saveGallery(e){e.preventDefault();const row={titulo:$('#galTitle').value.trim()||null,descricao:$('#galDescription').value.trim()||null,imagem_url:$('#galUrl').value.trim(),ativo:$('#galActive').checked};if(!row.imagem_url)return status('Informe a URL da imagem.');const r=galleryId?await sup().from('galeria').update(row).eq('id',galleryId):await sup().from('galeria').insert(row);if(r.error)return status('Não foi possível salvar a imagem.');status('Imagem adicionada à galeria.');resetGallery();loadGallery();showModule('gallery','Galeria')}
async function toggleGallery(id){const {data}=await sup().from('galeria').select('ativo').eq('id',id).single();if(!data)return;await sup().from('galeria').update({ativo:!data.ativo}).eq('id',id);loadGallery()}
async function deleteGallery(id){if(!confirm('Excluir esta imagem?'))return;const r=await sup().from('galeria').delete().eq('id',id);status(r.error?'Erro ao excluir.':'Imagem excluída.');loadGallery()}
function bind(){
  const routes={games:['games','Jogos',loadGames],gameEditor:['gameEditor','Novo jogo',resetGame],athletes:['athletes','Elenco',loadAthletes],athEditor:['athEditor','Novo atleta',resetAthlete],gallery:['gallery','Galeria',loadGallery]};
  Object.entries(routes).forEach(([id,[view,title,load]])=>{$(`[data-view="${view}"]`)?.addEventListener('click',()=>{showModule(id,title);load()})});
  $('#newGameBtn')?.addEventListener('click',()=>{resetGame();showModule('gameEditor','Novo jogo')});$('#gameForm')?.addEventListener('submit',saveGame);$('#newAthleteBtn')?.addEventListener('click',()=>{resetAthlete();showModule('athEditor','Novo atleta')});$('#athForm')?.addEventListener('submit',saveAthlete);$('#newGalleryBtn')?.addEventListener('click',()=>{resetGallery();showModule('galleryEditor','Nova imagem')});$('#galleryForm')?.addEventListener('submit',saveGallery);$('#newGalleryBtn2')?.addEventListener('click',()=>{resetGallery();showModule('galleryEditor','Nova imagem')});
  $('[data-view="galleryEditor"]')?.addEventListener('click',()=>showModule('galleryEditor','Nova imagem'));
}
window.addEventListener('load',()=>setTimeout(bind,0));
})();