plugins { id 'com.android.application' }

android {
    namespace 'br.com.selecaobaixagrande.app'
    compileSdk 36

    defaultConfig {
        applicationId 'br.com.selecaobaixagrande.app'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "Selecao-De-Baixa-Grande-" + variant.name + ".apk"
        }
    }
}
